---
version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6-stretch
  working_directory: ~/hello-stateful
  environment:
    LIBRARY: joatmon08
    CONTAINER_NAME: hello-stateful
    VERSION: 1.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build the runner
          command: |
            docker build $LIBRARY/$CONTAINER_NAME:latest .
            docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
      - run:
          name: Push the image to Docker Hub
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            docker push $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
            docker push $LIBRARY/$CONTAINER_NAME:latest

workflows:
  version: 2
  hello-stateful:
    jobs:
      - build